name = "webhook"
type = "typescript"
workers_dev = true
compatibility_date = "2021-09-25"
compatibility_flags = [ "nodejs_compat" ]

[build]
command = "NODE_OPTIONS=--openssl-legacy-provider npm install && NODE_OPTIONS=--openssl-legacy-provider npm run build"
[build.upload]
format = "modules"
dir = "./src"
main = "./index.ts"
